language: php

git:
  depth: 2

env:
  global:
    - OPCODE_CACHE=apc

matrix:
  include:
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: nightly
    - php: 7.1
    - php: 7.0
      env:
      - LINT=true
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3

  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer update

script:
  - if [[ $LINT = true ]]; then
      composer assert:cs-lint;
      ./bin/travis/lint-docs;
    fi
  - php vendor/bin/phpunit
